### ISSUE TITLE
HTML comment

### ISSUE THREAD

**Issue by Kiho** [kuhlaid/svelte2#7]
Comment like this https://github.com/kuhlaid/svelte2/blob/master/src/ApiSettingsIdb.svelte#L1 
made debugging very hard. It's much easier if you move that as JS comment.
```js
<script>
/* 
    @abstract This component will be used to update the URL of the server-side API to connect to.
    We need to read the localstorage strApiUrl value and copy to a writable variable.

    @todo Check the session token with the API server.
    Check if the user has an active session with a back-end API and save session.
*/ 
...
</script>
```

**Comment by kuhlaid** [comment]
Thanks Kiho, I wasn't receiving comment notifications so am just getting around to checking the repo. Just curious why the HTML comments would be causing debugging issues?

**Comment by Kiho** [comment]
Do not know why but variable inspection at break point does not match if html comment was used.
